# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.18.4

# Mod Properties
mod_version=1.0.0
maven_group=com.modforge.writethecodeforaminecraftmodthat
archives_base_name=write-the-code-for-a-minecraft-mod-that--mp4yuwm4

# Dependencies
fabric_version=0.141.4+1.21.11
